# Generated by Django 5.0.1 on 2025-12-14 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300)),
                ('ai_tools', models.JSONField(default=list)),
                ('target_users', models.CharField(blank=True, choices=[('students', 'Students'), ('developers', 'Developers'), ('business', 'Business Users'), ('general', 'General Users')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('output_type', models.CharField(blank=True, choices=[('single_component', 'Single Component'), ('page', 'Page'), ('multi_page_app', 'Multi-Page App'), ('api_only', 'API Only'), ('full_project', 'Full Project')], max_length=20)),
                ('expected_outputs', models.JSONField(default=dict)),
                ('frontend_framework', models.CharField(blank=True, max_length=50)),
                ('styling', models.CharField(blank=True, max_length=50)),
                ('backend_framework', models.CharField(blank=True, max_length=50)),
                ('database', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
